[tools]
ruby = "3.2.0"
watchexec = "latest"

[env]
RACK_ENV = "development"
BOOKLET_ENV = "development"
BOOKLET_LOG_LEVEL = "DEBUG"

[tasks.setup]
description = "Dev setup"
run = ["bundle install"]

[tasks.test]
description = "Run the tests"
run = "bin/test"
alias = "t"

[tasks."test:watch"]
description = "Run the tests whenever a file changes"
run = "mise watch test"
alias = "tw"
